#!/bin/bash
# Raspberry Pi Wireless Hotspot Installation Script

cp ./config-files/udhcpd_unblockus.conf /etc/udhcpd.conf
cp ./config-files/udhcpd /etc/default
cp ./config-files/udhcpd.service /lib/systemd/system/
systemctl enable udhcpd.service
