#!/bin/bash
# Raspberry Pi Wireless Hotspot Installation Script

# FIX FOR: Failed to start hostapd.service: Unit hostapd.service is masked.
# FROM: https://www.raspberrypi.org/forums/viewtopic.php?t=235598
systemctl unmask hostapd
systemctl enable hostapd
systemctl start hostapd

touch /var/lib/misc/udhcpd.leases

echo "Initialising access point"
service hostapd start
update-rc.d hostapd enable

echo "Initialising DHCP server"
service udhcpd start
update-rc.d udhcpd enable

echo "=================== Configuration complete! ===================="
echo "Perform ''reboot''"
