#!/bin/bash
# Raspberry Pi Wireless Hotspot Installation Script

echo "Configuring hostapd"
readonly DEFAULTPWD="0123456789A"
readonly DEFAULTSSID="RaspberryPiFi"
readonly DEFAULTCHANNEL=8

read -r -p "Do you want to use the wifi defaults of password=${DEFAULTPWD}, ssid=${DEFAULTSSID}, and channel=${DEFAULTCHANNEL}? [y/N] " althostapdresponse

if [[ $althostapdresponse =~ ^([yY][eE][sS]|[yY])$ ]]
then
	cp ./config-files/hostapd.conf /etc/hostapd
else
	_PASSWORD1="0"
	_PASSWORD2="1"
	read -r -s -p "Please enter a new password at least 8 characters long (length is not checked): " _PASSWORD1
	echo
	read -r -s -p "Please enter the new password again: " _PASSWORD2
	echo
	while [ ${_PASSWORD1} != ${_PASSWORD2} ]
	do
		echo "Password mismatch please try again."
		read -r -s -p "Please enter a new password at least 8 characters long (length is not checked): " _PASSWORD1
		echo
		read -r -s -p "Please enter the new password again: " _PASSWORD2
		echo
	done
	read -r -p "Please enter a new ssid: " _SSID
	# Sentry for the channel selection
	_SENTRY="0"
	while [ ${_SENTRY} != "1" ]
	do
		read -r -p "Please enter a new channel from 1 to 11: " _CHANNEL
		if [ ${_CHANNEL} == ${_CHANNEL//[^0-9]/} ] && [ ${_CHANNEL} -lt 12 ]  && [ ${_CHANNEL} -gt 0 ]
		then
			echo "You selected channel $_CHANNEL."
			_SENTRY="1"
		else
			echo "Invalid entry received of ${_CHANNEL} ."
		fi
	done
	CONTENTS=$(<./config-files/hostapd.conf)
	CONTENTS=${CONTENTS//wpa_passphrase=${DEFAULTPWD}/wpa_passphrase=${_PASSWORD1}}
	CONTENTS=${CONTENTS//ssid=${DEFAULTSSID}/ssid=${_SSID}}
	CONTENTS=${CONTENTS//channel=${DEFAULTCHANNEL}/channel=${_CHANNEL}}
	echo "${CONTENTS}" > /etc/hostapd/hostapd.conf
fi
cp ./config-files/hostapd /etc/default
